ScoutingApp/DjangoExample/DjangoExample/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^firstApp/', include('firstApp.urls')),
    url(r'^junction_table/', include('junction_table.urls', namespace="junction_table")),
]

ScoutingApp/DjangoExample/firstApp/urls.py
'''
Created on Oct 9, 2015

@author: PJ
'''
from django.conf.urls import url
from . import views


urlpatterns = [
               url(r'^$', views.index, name='index'),
               url(r'^person/(?P<person_id>[0-9]+)$', views.view_person, name='personPage'),
               url(r'^pet/(?P<pet_id>[0-9]+)$', views.view_pet, name='petPage'),
              ]

ScoutingApp/DjangoExample/junction_table/urls.py
'''
Created on Oct 9, 2015

@author: PJ
'''
from django.conf.urls import url
from . import views


urlpatterns = [
               url(r'^$', views.index, name='index'),
               url(r'^players/$', views.view_all_players, name='all_players'),
               url(r'^players/(?P<player_id>[0-9]+)$', views.view_player, name='view_player'),
               url(r'^games/$', views.view_all_games, name='all_games'),
               url(r'^games/(?P<game_id>[0-9]+)$', views.view_game, name='view_genre'),
               url(r'^genres/$', views.view_all_genres, name='alL_genres'),
               url(r'^genres/(?P<genre_id>[0-9]+)$', views.view_genre, name='view_genre'),

               url(r'^create_genre$', views.create_genre, name='create_genre'),
               url(r'^create_game$', views.create_game, name='create_game'),
               url(r'^create_player$', views.create_player, name='create_player'),
               url(r'^(?P<player_id>[0-9]+)/add_game_to_player$', views.add_game_to_player, name='add_game_to_player'),
               ]

ScoutingApp/DjangoExample/firstApp/models.py
from django.db import models


class Person(models.Model):

    personName = models.CharField(max_length=200)
    personAge = models.IntegerField(default=14)

    def is_a_minor(self):
        return self.personAge

    def __str__(self):
        return "%s (%s)" % (self.personName, self.personAge)


class Pet(models.Model):

    myOwner = models.ForeignKey(Person)
    petName = models.CharField(max_length=200)

    def __str__(self):
        return "%s" % (self.petName)

ScoutingApp/DjangoExample/junction_table/models.py
from django.db import models

# Create your models here.


class GameGenre(models.Model):

    genreName = models.CharField(max_length=100)
    genreDescription = models.CharField(max_length=300)

    def __str__(self):
        return "%s" % (self.genreName)


class Game(models.Model):

    gameName = models.CharField(max_length=100)
    genre = models.ForeignKey(GameGenre)

    def __str__(self):
        return "%s, %s" % (self.gameName, self.genre)


class Players(models.Model):

    playerName = models.CharField(max_length=100)
    games = models.ManyToManyField(Game)

    def __str__(self):
        return "%s" % (self.playerName)

ScoutingApp/DjangoExample/firstApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Person, Pet


def index(request):

    people = Person.objects.all()
    context = {"all_people": people}
    return render(request, 'firstApp/index.html', context)


def view_person(request, person_id):

    person = Person.objects.get(id=person_id)
    context = {"my_name": person.personName, "my_age": person.personAge, "my_pets": person.pet_set.all()}
    return render(request, 'firstApp/person.html', context)


def view_pet(request, pet_id):

    pet = Pet.objects.get(id=pet_id)
    context = {"pet_name": pet.petName}
    return render(request, 'firstApp/pet.html', context)

ScoutingApp/DjangoExample/junction_table/views.py
from django.shortcuts import render, get_object_or_404
from junction_table.models import Game, GameGenre, Players
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.


def index(request):

    context = {}
    return render(request, 'junction_table/index.html', context)


def view_all_games(request):

    context = {"games": Game.objects.all(), "available_genres": GameGenre.objects.all()}
    return render(request, 'junction_table/viewGames.html', context)


def view_all_players(request):

    context = {"players": Players.objects.all()}
    return render(request, 'junction_table/viewPlayers.html', context)


def view_all_genres(request):

    context = {"genres": GameGenre.objects.all()}
    return render(request, 'junction_table/viewGenres.html', context)


def view_game(request, game_id):

    game = get_object_or_404(Game, id=game_id)

    context = {"game": game}
    return render(request, 'junction_table/viewGame.html', context)


def view_genre(request, genre_id):

    genre = get_object_or_404(GameGenre, id=genre_id)

    context = {"genre": genre}
    return render(request, 'junction_table/viewGenre.html', context)


def view_player(request, player_id):

    player = get_object_or_404(Players, id=player_id)
    games = Game.objects.filter(players__id=player_id)
    available_games = Game.objects.all()

    context = {"player": player, "games": games, "available_games": available_games}
    return render(request, 'junction_table/viewPlayer.html', context)


def create_genre(request):

    try:
        GameGenre.objects.create(genreName=request.POST['genreName'], genreDescription=request.POST['genreDescription'])
    except:
        raise  # TODO: fix to something better

    return HttpResponseRedirect(reverse('junction_table:alL_genres'))


def create_game(request):

    try:
        genre = get_object_or_404(GameGenre, genreName=request.POST['gameGenre'])
        Game.objects.create(gameName=request.POST['gameName'], genre=genre)
    except:
        raise  # TODO: fix to something better

    return HttpResponseRedirect(reverse('junction_table:all_games'))


def create_player(request):

    try:
        Players.objects.create(playerName=request.POST['playerName'])
    except:
        raise  # TODO: fix to something better

    return HttpResponseRedirect(reverse('junction_table:all_players'))


def add_game_to_player(request, player_id):

    player = get_object_or_404(Players, id=player_id)
    game = get_object_or_404(Game, gameName=request.POST['gameName'])

    try:
        player.games.add(game)
    except:
        raise  # TODO: fix to something better

    return HttpResponseRedirect(reverse('junction_table:view_player', args=(player.id,)))

ScoutingApp/DjangoExample/firstApp/templates/firstApp/index.html
<html>
<head>


{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'firstApp/style.css' %}" />

<title>Welcome!</title>
</head>


<body>
Hello World! My First <a target="_blank" href="https://www.youtube.com/watch?v=eUdM9vrCbow">Django</a> App!
<br><br><br>
Check out our peeps
{% if all_people %}
    <ul>
    {% for person in all_people %}
        <li><a href="/firstApp/person/{{ person.id }}">{{ person.personName }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Everyone is dead!</p>
{% endif %}

</body>
</html>

ScoutingApp/DjangoExample/firstApp/templates/firstApp/person.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'firstApp/style.css' %}" />

<title>{{my_name}}'s Page</title>
</head>


<body>

<h1> {{my_name}} </h1>
Sup!?  My name is {{my_name}} and I am {{my_age}} years old.  Check out all of my sweet pets


{% if my_pets %}
    <ol>
    {% for pet in my_pets %}
        <li><a href="/firstApp/pet/{{ pet.id }}">{{ pet.petName }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>Lol, jk.  I don't have pets.</p>
{% endif %}

</body>
</html>

ScoutingApp/DjangoExample/firstApp/templates/firstApp/pet.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'firstApp/style.css' %}" />

Bark/Meow/Blub Blub.  I'm just a pet named {{ pet_name }} , idk what you expected...

ScoutingApp/DjangoExample/junction_table/templates/junction_table/banner.html
<div class="nav"
<ul>
 <li> <a href="/junction_table/">Home</a> </li>
 <li> <a href="/junction_table/games/">Games</a> </li>
 <li> <a href="/junction_table/genres/">Genres</a> </li>
 <li> <a href="/junction_table/players/">Players</a> </li>
 
</ul>
<br>

</div>

ScoutingApp/DjangoExample/junction_table/templates/junction_table/index.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'junction_table/style.css' %}" />
<title>Welcome!</title>
</head>
<body>

{% include "junction_table/banner.html" %}

<h1>Welcome to the video game store!</h1>

We currently have {{ num_players }} players playing {{ num_games}} different games. <br><br>
Look around at our collection of <a href="/junction_table/games/">games</a> and <a href="/junction_table/genres">genres</a> 

</body>
</html>

ScoutingApp/DjangoExample/junction_table/templates/junction_table/viewGame.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'junction_table/style.css' %}" />
<title>{{ game.gameName }}</title>
</head>
<body>

{% include "junction_table/banner.html" %}

<h1> Viewing <u><i>{{ game.gameName }}</i></u> </h1>

{{ game.gameName }} is an <a href="/junction_table/genres/{{game.genre.id}}">{{game.genre}}</a> game 
that has {{ game.players_set.all|length }} players.<br>

{% if game.players_set.all|length != 0 %}
<ul>
  {% for player in game.players_set.all %}
  <li><a href="/junction_table/players/{{player.id}}">{{player.playerName}}</a></li>
  {% endfor %}
</ul>
{% endif %}

</body>
</html>

ScoutingApp/DjangoExample/junction_table/templates/junction_table/viewGames.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'junction_table/style.css' %}" />
<title>All Games</title>
</head>
<body>

{% include "junction_table/banner.html" %}

<h1> Games </h1>

<table>
<tr>
  <th> Title </th>
  <th> Genre </th>
  <th> Players </th>
</tr>

{% for game in games %}
<tr>
    <td><a href="/junction_table/games/{{game.id}}">{{game.gameName}}</a></td>
    <td><center><a href="/junction_table/genres/{{game.genre.id}}"> {{game.genre}}</center></a> </td>
    <td><center>{{game.players_set.all|length}}<center></td>
</tr>
{% endfor %}
    
</table>


{% if available_genres|length != 0 %}
<br><br>
<h2>Add Game</h2>
<form action="{% url 'junction_table:create_game' %}" method="post">
{% csrf_token %}
<table style="width:auto">
  <tr>
     <td>Name</td>
     <td><input type="text" name="gameName" ></td>
   </tr>
  <tr>
    <td>Genre</td>
  
    <td>
     <select name="gameGenre" style="width:100%">
     {% for genre in available_genres %}
       <option value="{{genre.genreName}}">{{genre.genreName}}</option>
     {% endfor %}
     </select>
     </td>
  </tr>
     
</table>

<input type="submit" value="Add" />
</form>
{% endif %}

</body>
</html>

ScoutingApp/DjangoExample/junction_table/templates/junction_table/viewGenre.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'junction_table/style.css' %}" />
<title>{{ genre.genreName }}</title>
</head>
<body>

{% include "junction_table/banner.html" %}

<h1> Viewing the <u><i>{{ genre.genreName }}</i></u> genre</h1>

Description: {{ genre.genreDescription }}<br>

<br><br>

We have  {{ genre.game_set.all|length }} games in stock.
{% if y != 0 %}
<ul>
  {% for game in genre.game_set.all %}
  <li><a href="/junction_table/games/{{game.id}}">{{game.gameName}}</a></li>
  {% endfor %}
</ul>
{% endif %}


</body>
</html>

ScoutingApp/DjangoExample/junction_table/templates/junction_table/viewGenres.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'junction_table/style.css' %}" />
<title>All Genres</title>
</head>
<body>

{% include "junction_table/banner.html" %}


<h1> Genres </h1>

<table>
<tr>
  <th> Genre </th>
  <th> Description </th>
  <th> Games </th>
</tr>

{% for genre in genres %}
<tr>
    <td><a href="/junction_table/genres/{{genre.id}}">{{genre.genreName}}</a></td>
    <td><center>{{genre.genreDescription}}</center></td>
    <td><center>{{genre.game_set.all|length}}<center></td>
</tr>
{% endfor %}
    
</table>

<br><br>
<h2>Add Genre</h2>
<form action="{% url 'junction_table:create_genre' %}" method="post">
{% csrf_token %}
<table style="width:auto">
  <tr><td>Name        </td><td><input type="text" name="genreName" ></td></tr>
  <tr><td>Description </td><td><input type="text" name="genreDescription"></td></tr>
</table>

<input type="submit" value="Add" />
</form>

</body>
</html>

ScoutingApp/DjangoExample/junction_table/templates/junction_table/viewPlayer.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'junction_table/style.css' %}" />
<title>{{ player.playerName }}'s Page</title>
</head>
<body>

{% include "junction_table/banner.html" %}

<h1> Welcome to {{ player.playerName }}'s page </h1>

{{ player.playerName }} plays {{ games|length }} games

<br><br>

{% if games|length != 0 %}
<h2>{{ player.playerName }}'s games</h2>
<ul>
{% for game in games %}
  <li> <a href="/junction_table/games/{{game.id}}">{{game.gameName}}</a> </li>
{% endfor %}
{% endif %}
</ul>


{% if available_games|length != 0 %}

<br><br>
<h2>Add Game</h2>
<form action="{% url 'junction_table:add_game_to_player' player.id %}" method="post">
{% csrf_token %}
<table style="width:auto">
  <tr>
     <td>Game Name:</td><td>
     <select name="gameName">
     {% for game in available_games %}
       <option value="{{game.gameName}}">{{game.gameName}}</option>
     {% endfor %}
     </select>
     </td>
  </tr>
</table>

<input type="submit" value="Add" />
</form>

{% endif %}


</body>
</html>

ScoutingApp/DjangoExample/junction_table/templates/junction_table/viewPlayers.html
<html>
<head>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'junction_table/style.css' %}" />
<title>All Players</title>
</head>
<body>

{% include "junction_table/banner.html" %}


<h1> Players </h1>

<table>
<tr>
  <th> Player </th>
  <th> Games </th>
</tr>

{% for player in players %}
<tr>
    <td><a href="/junction_table/players/{{player.id}}">{{player.playerName}}</a></td>
    <td><center>{{player.games.all|length}}</center></td>
</tr>
{% endfor %}
    
</table>


<br><br>
<h2>Add Player</h2>
<form action="{% url 'junction_table:create_player' %}" method="post">
{% csrf_token %}
<table style="width:auto">
  <tr><td>Name:       </td><td><input type="text" name="playerName" ></td></tr>
</table>

<input type="submit" value="Add" />
</form>

</body>
</html>